/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Table;

//import com.mysql.jdbc.Connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Compaq
 */
public class Table_Creation extends javax.swing.JFrame {
String pwd="MyNewPass";
    /**
     * Creates new form Table_Creation
     */
    public Table_Creation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Create Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

long Account=102581800;
        try {            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            int Bank_Table=stmt.executeUpdate("create table Bank_Table"
                    + "(Account_no varchar(20) primary key,"
                    + "Name_of_Account_Holder varchar(50),"
                    + "Balance varchar(20),"
                    + "Card_no varchar(20),"
                    + "Phone_no varchar(20),"
                    + "Date_of_Account_Creation date,"
                    + "Account_Type varchar(20))");
            int Acc=stmt.executeUpdate("create table Accno"
                    + "(Acc varchar(20) primary key)");
            int Accno=stmt.executeUpdate("insert into Accno values"
                    + "(102581820)");
            int Bank_Account=stmt.executeUpdate("insert into bank_table"
                    + "(Account_no,Name_of_Account_Holder,Balance,Card_no,Phone_no,Date_of_Account_Creation,Account_Type)"
                    + " VALUES('102581801','Asha Sharma',530000,'100200580','9632758741','2010-09-04','Saving Account'),"
                    + "('102581802','Ashish Mishra',746200,'100200581','9872456328','2011-07-04','Saving Account'),"
                    + "('102581803','Amit Pathak',365900,'100200582','8745981264','2006-04-07','Saving Account'),"
                    + "('102581804','Anmol Yadav',563000,'100200583','9124753681','2012-08-11','Current Account'),"
                    + "('102581805','Rahul Singh',196000,'102586000','8723419853','2012-04-16','Saving Account'),"
                    + "('102581806','Sunil Mishra',325000,'100258001','9172283671','2007-01-25','Current Account'),"
                    + "('102581807','Anil Khanna',126340,'102500810','8126677291','2014-08-26','Saving Account'),"
                    + "('102581808','Shyam Mishra',150500,'104500800','8845112769','1999-05-13','Saving Account'),"
                    + "('102581809','Anand Dubey',96000,'100520080','8477521198','2013-04-07','Saving Account'),"
                    + "('102581810','Anand Bakshi',563200,'152800200','9996135718','2013-04-07','Saving Account'),"
                    + "('102581811','Sanjay Khanna',410000,'100240080','9912745581','2013-04-08','Saving Account'),"
                    + "('102581812','Anand Bakshi',198522,'100500580','9877413528','2010-05-17','Saving Account'),"
                    + "('102581813','Sapan Dubey',130299,'100250081','8884124793','2009-02-24','Current Account'),"
                    + "('102581814','Alok Sharma',23500,'102058100','9841225748','2010-05-21','Current Account'),"
                    + "('102581815','Amit Khanna',5995,'100205081','9871245781','2013-05-01','Saving Account'),"
                    + "('102581816','Anil Yadav',96320,'100200501','2562230','2001-06-21','Saving Account'),"
                    + "('102581818','Anil Kumar',326000,'100200581','9685124781','2010-05-01','Current Account'),"
                    + "('102581819','Ashish Dubey',36200,'150020081','2235142','2013-05-07','Saving Account'),"
                    + "('102581820','Ashish Mishra',36200,'100502800','9652102475','2013-04-21','Saving Account')");           
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_Creation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_Creation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
