
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Add_Account extends javax.swing.JFrame {
    String pwd="MyNewPass";

    /**
     * Creates new form Bank_management_system2
     */
    public Add_Account() {
        initComponents();
        
        this.setLocation(200,80);
        this.setSize(900,430);
        Date Date=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        jLabel1.setText(""+df.format(Date));
        CurrentRB.setSelected(true); 
        AccTF.setEditable(false);
        AccTF.setFocusable(false);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        ctd();
    }
public void ctd()
{
String Acc="";
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("Select * from Accno");
            while (rs.next()) {                
                
                Acc=rs.getString("Acc");
                
            }
            
        int Ac=Integer.parseInt(Acc);
        int ac=Ac+1;
        AccTF.setText(""+ac);
        

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());

        }        

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Account_TyperBG = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Account_Type = new javax.swing.JPanel();
        CurrentRB = new javax.swing.JRadioButton();
        SavingRB = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        AccTF = new javax.swing.JTextField();
        BalanceTF = new javax.swing.JTextField();
        CardTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        DoJTF = new javax.swing.JTextField();
        AddAccBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ClearBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create Account");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Card no.");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(76, 262, 51, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Creating Account");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(383, 23, 156, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Phone no.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(76, 318, 61, 15);

        Account_Type.setBackground(new java.awt.Color(255, 255, 255));
        Account_Type.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Account Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        Account_Type.setToolTipText("Account Type");

        CurrentRB.setBackground(new java.awt.Color(255, 255, 255));
        Account_TyperBG.add(CurrentRB);
        CurrentRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CurrentRB.setText("Current Account");

        SavingRB.setBackground(new java.awt.Color(255, 255, 255));
        Account_TyperBG.add(SavingRB);
        SavingRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SavingRB.setText("Saving Account");

        javax.swing.GroupLayout Account_TypeLayout = new javax.swing.GroupLayout(Account_Type);
        Account_Type.setLayout(Account_TypeLayout);
        Account_TypeLayout.setHorizontalGroup(
            Account_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Account_TypeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Account_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SavingRB)
                    .addComponent(CurrentRB))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        Account_TypeLayout.setVerticalGroup(
            Account_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Account_TypeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CurrentRB)
                .addGap(26, 26, 26)
                .addComponent(SavingRB)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(Account_Type);
        Account_Type.setBounds(590, 90, 247, 139);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Date of Account Creation");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(76, 375, 151, 15);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        getContentPane().add(NameTF);
        NameTF.setBounds(261, 93, 256, 30);

        AccTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTFActionPerformed(evt);
            }
        });
        getContentPane().add(AccTF);
        AccTF.setBounds(261, 148, 256, 30);
        getContentPane().add(BalanceTF);
        BalanceTF.setBounds(261, 204, 256, 30);
        getContentPane().add(CardTF);
        CardTF.setBounds(261, 260, 256, 30);

        PhoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneTFActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneTF);
        PhoneTF.setBounds(261, 316, 256, 30);
        getContentPane().add(DoJTF);
        DoJTF.setBounds(261, 373, 256, 30);

        AddAccBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddAccBTN.setText("Add Account");
        AddAccBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddAccBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AddAccBTN);
        AddAccBTN.setBounds(150, 470, 170, 30);

        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(800, 490, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name of Account holder");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(76, 95, 145, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Account no.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(76, 150, 71, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Amount:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(76, 206, 70, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 30, 167, 20);

        ClearBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBTN);
        ClearBTN.setBounds(450, 470, 80, 30);

        jLabel3.setText("+91");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 320, 30, 30);

        jLabel10.setText("(Proper Format :YYYY-MM-DD)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 380, 170, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Frame(){
     
        if (new Add_Account().isShowing()) {
          new Login().setVisible(true);
          this.setVisible(false);
        }
     
    }
    
    
    private void AddAccBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccBTNActionPerformed

String NameAcc,Balance,DoJ,Acctype = null,AccNo;
long CardNo=0,Phone=0;
int a=0,a1=0;
        NameAcc = NameTF.getText();
        AccNo = AccTF.getText();
        Balance = BalanceTF.getText();
        DoJ = DoJTF.getText();          
    
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        try {
            
            Date Acda=df.parse(DoJ);
            a1=1;
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Date in proper format\nThat is : YYYY-MM-DD\nAnd all the details properly");
            a1=0;
        }
        if(a1!=0)
        {
            try
            {
            CardNo = Long.parseLong(CardTF.getText());
            Phone = Long.parseLong(PhoneTF.getText());
            long b=Long.parseLong(Balance);
            a=1;
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(this,"Please enter all details properly");
            a=0;
            }
        
        if(NameAcc.trim().equals("")||AccNo.trim().equals("")||Balance.trim().equals("")||DoJ.trim().equals(""))
        {
            if(a==1)
            {
                JOptionPane.showMessageDialog(this,"Please enter all details properly");
            }
        }
        else{
        try {
                    
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection)
        DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
        Statement stmt=con.createStatement();
                
        if (CurrentRB.isSelected())     
        {
            Acctype="Current Account";
        }
        else if(SavingRB.isSelected())
        {
            Acctype="Saving Account";
        }   
        if (Phone<1000000000||Phone>10000000000L) {
                 
                JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone No");
                return;
            
        }
        if (Integer.parseInt(Balance)<500) {
                
                JOptionPane.showMessageDialog(this, "Please Create Account with more than Rs. 500");
                return;
                
        }
            int rows=stmt.executeUpdate("insert into Bank_Table(Account_no,Name_of_Account_Holder,Balance,Card_no,Phone_no,Date_of_Account_Creation,Account_Type) values('"+(AccNo)+"','"+(NameAcc)+"',"+(Balance)+","+(CardNo)+","+(Phone)+",'"+(DoJ)+"','"+(Acctype)+"')");
            JOptionPane.showMessageDialog(this, "Account Created");
            
            int nac=Integer.parseInt(AccNo)-1;
            int Ac=Integer.parseInt(AccNo);            
            int ac=Ac+1;            
            int rowss=stmt.executeUpdate("update Accno set Acc='"+(AccNo)+"' where Acc='"+(nac)+"'");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        }
        }
    }//GEN-LAST:event_AddAccBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed

       new Bank_management_system().setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_BackBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed

BalanceTF.setText("");
CardTF.setText("");
DoJTF.setText("");
NameTF.setText("");
PhoneTF.setText("");
CurrentRB.setSelected(true);
SavingRB.setSelected(false);

// TODO add your handling code here:
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void AccTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccTFActionPerformed

    private void PhoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneTFActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered

SimpleDateFormat df=new SimpleDateFormat("dd-MMM-yyyy hh:mm a");
Date Date=new Date();
jLabel1.setText(""+df.format(Date));

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited

Date Date=new Date();
SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
jLabel1.setText(""+df.format(Date)); 
        

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccTF;
    private javax.swing.JPanel Account_Type;
    private javax.swing.ButtonGroup Account_TyperBG;
    private javax.swing.JButton AddAccBTN;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTextField BalanceTF;
    private javax.swing.JTextField CardTF;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JRadioButton CurrentRB;
    private javax.swing.JTextField DoJTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JRadioButton SavingRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
