
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Admin_Login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login
     */
    public Admin_Login() {
        initComponents();
        
        this.setSize(623,350);
        this.setLocation(340,200);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginBTN = new javax.swing.JButton();
        NameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassPF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Adnimistrator Login User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 190, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Asministrator Login Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 150, 184, 15);

        LoginBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginBTN.setText("Administrator Login");
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        LoginBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginBTNKeyPressed(evt);
            }
        });
        getContentPane().add(LoginBTN);
        LoginBTN.setBounds(220, 260, 155, 23);
        getContentPane().add(NameTF);
        NameTF.setBounds(360, 80, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Administrator Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 23, 177, 22);

        PassPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassPFKeyPressed(evt);
            }
        });
        getContentPane().add(PassPF);
        PassPF.setBounds(360, 140, 180, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdLogin.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed

        if ("bank".equals(NameTF.getText().trim()) && "12".equals(new String(PassPF.getPassword()).trim())) {
                
                new Change_Details().setVisible(true);
                this.setVisible(false);
                
        }else{
            
                JOptionPane.showMessageDialog(this, "You do not Have Administrator Authorities");
                new Modify_Account().setVisible(true);
                this.setVisible(false);
            
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNActionPerformed

    private void LoginBTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginBTNKeyPressed
     
        if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            
            if ("bank".equals(NameTF.getText().trim()) && "12".equals(new String(PassPF.getPassword()).trim())) {
                
                new Change_Details().setVisible(true);
                this.setVisible(false);
                
            }else{
            
                JOptionPane.showMessageDialog(this, "You do not Have Administrator Authorities");
                new Modify_Account().setVisible(true);
                this.setVisible(false);
            
            }
            
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNKeyPressed

    private void PassPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassPFKeyPressed

        if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            
            if ("bank".equals(NameTF.getText().trim()) && "12".equals(new String(PassPF.getPassword()).trim())) {
                
                new Change_Details().setVisible(true);
                this.setVisible(false);
                
            }else{
            
                JOptionPane.showMessageDialog(this, "You do not Have Administrator Authorities");
                new Modify_Account().setVisible(true);
                this.setVisible(false);
            
            }
            
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_PassPFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBTN;
    private javax.swing.JTextField NameTF;
    private javax.swing.JPasswordField PassPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
