
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Change_Details extends javax.swing.JFrame {
int r=0;
String pwd="MyNewPass";
int eq=0;

/**
     * Creates new form Change_Details
     */
    public Change_Details() {
        initComponents();
        
        this.setSize(1290,740);
        

    
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        ctd("select * from Bank_Table");
    }

    public void ctd(String qry)
{
        DefaultTableModel tm=(DefaultTableModel)DetailsTBL.getModel();
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(qry);
             int rows=tm.getRowCount();
            if (rows>0) {
                
                for (int i = 0; i < rows; i++) {
                    
                    tm.removeRow(0);
                    
                }}               
            while (rs.next()) {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                String date=rs.getString("Date_of_Account_creation");
                String phone=rs.getString("Phone_no");
                tm.addRow(new Object[]{acc,name,balance,card,phone,date,Acctype});
                        
            }
        eq=1;
        if(tm.getRowCount()==0)
        {
        JOptionPane.showMessageDialog(this,"Please enter a valid Account Number");
        eq=0;
        AccTF.setText("");
        ctd("select * from Bank_Table");
  
        
        }    
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }

}  
public void ctup(String qr1,String qr2)
{
try {
            
            DefaultTableModel tm=(DefaultTableModel)DetailsTBL.getModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            int rows=stmt.executeUpdate(qr1);
            ResultSet rs=stmt.executeQuery(qr2);
            int rowss=tm.getRowCount();
            if (rowss>0) {
                
                for (int i = 0; i < rowss; i++) {
                    
                    tm.removeRow(0);
                    
                }}
            while (rs.next()) {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                String date=rs.getString("Date_of_Account_creation");
                String phone=rs.getString("Phone_no");
                tm.addRow(new Object[]{acc,name,balance,card,phone,date,Acctype});
                
            }
            
                        
        } catch (Exception e){
    
            JOptionPane.showMessageDialog(this, e.getMessage());
    
        }
}
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DetailsTBL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BackBTN = new javax.swing.JButton();
        AccTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CardTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PhoneTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TypeCoB = new javax.swing.JComboBox();
        DateTF = new javax.swing.JTextField();
        NameBTN = new javax.swing.JButton();
        CardBTN = new javax.swing.JButton();
        PhoneBTN = new javax.swing.JButton();
        AccTypeBTN = new javax.swing.JButton();
        DateBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ClearBTN = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Change Details");
        setForeground(Color.yellow
        );
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        DetailsTBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DetailsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account no.", "Name of Account holder", "Balance", "Card no.", "Phone no.", "Date of Account Creation", "Account Type"
            }
        ));
        DetailsTBL.setEnabled(false);
        jScrollPane1.setViewportView(DetailsTBL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 22, 1260, 270);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BackBTN);
        BackBTN.setBounds(1190, 660, 70, 30);

        AccTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccTFKeyPressed(evt);
            }
        });
        jPanel1.add(AccTF);
        AccTF.setBounds(220, 320, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Enter Account Number: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 320, 180, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        NameTF.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Card No");

        CardTF.setEnabled(false);
        CardTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date");

        PhoneTF.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Phone No");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Account Type");

        TypeCoB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TypeCoB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Account", "Saving Account" }));
        TypeCoB.setEnabled(false);

        DateTF.setEnabled(false);

        NameBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameBTN.setText("Change Name");
        NameBTN.setEnabled(false);
        NameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBTNActionPerformed(evt);
            }
        });

        CardBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CardBTN.setText("Change Card No");
        CardBTN.setEnabled(false);
        CardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardBTNActionPerformed(evt);
            }
        });

        PhoneBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PhoneBTN.setText("Change Phone No");
        PhoneBTN.setEnabled(false);
        PhoneBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneBTNActionPerformed(evt);
            }
        });

        AccTypeBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AccTypeBTN.setText("Change Account Type");
        AccTypeBTN.setEnabled(false);
        AccTypeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTypeBTNActionPerformed(evt);
            }
        });

        DateBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateBTN.setText("Change Date");
        DateBTN.setEnabled(false);
        DateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateBTNActionPerformed(evt);
            }
        });

        jLabel7.setText("+91");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CardTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TypeCoB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccTypeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NameBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhoneBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TypeCoB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccTypeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 390, 650, 300);

        ClearBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ClearBTN);
        ClearBTN.setBounds(800, 640, 120, 50);

        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(980, 640, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1300, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed

        new Modify_Account().setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_BackBTNActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void AccTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccTFKeyPressed
if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {    
        int z=0;
long Acc1=0;
try
{
Acc1=Long.parseLong(AccTF.getText());
z=1;
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,"Please enter Account number in proper format");
    AccTF.setText("");
}

if(z==1){
String Acc=""+Acc1;

Acc="select * from Bank_Table where Account_no="+(Acc)+"";
        
ctd(Acc);
if(AccTF.getText().trim().equals(""))
{}
else{
if(eq==1)
{
    NameBTN.setEnabled(true);
    
    AccTypeBTN.setEnabled(true);
    
    CardBTN.setEnabled(true);
    ClearBTN.setEnabled(true);
    DateBTN.setEnabled(true);
    DateTF.setEnabled(true);
    NameTF.setEnabled(true);
    PhoneBTN.setEnabled(true);
    PhoneTF.setEnabled(true);
    TypeCoB.setEnabled(true);
    CardTF.setEnabled(true);
            
}}
}        
}

// TODO add your handling code here:
    }//GEN-LAST:event_AccTFKeyPressed

    private void NameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBTNActionPerformed

String Acc=AccTF.getText(); 
String Name=NameTF.getText();
if(Acc.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter Account number");
}
else if(Name.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter a Name");
}

else
{
    String s1="update bank_table set Name_of_Account_Holder='"+(Name)+"' where Account_no='"+(Acc)+"'";
    String s2="select * from Bank_Table where Account_no="+(Acc)+"";
    ctup(s1,s2);
}   
// TODO add your handling code here:
    }//GEN-LAST:event_NameBTNActionPerformed

    private void CardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardBTNActionPerformed

String Acc=AccTF.getText(); 
String Card=CardTF.getText();
if(Acc.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter Account number");
}
else if(Card.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter a Card number");
}
else
{
    String s1="update bank_table set Card_no='"+(Card)+"' where Account_no='"+(Acc)+"'";
    String s2="select * from Bank_Table where Account_no="+(Acc)+"";
    ctup(s1,s2);
}   

    }//GEN-LAST:event_CardBTNActionPerformed

    private void PhoneBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneBTNActionPerformed

String Acc=AccTF.getText(); 
long Phone=0L;
int xm=0;
try{
   Phone=Long.parseLong(PhoneTF.getText());
   xm=1;
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this, "Please enter Phone number properly");
PhoneTF.setText("");
}
if(xm==1){
if (Phone<1000000000||Phone>10000000000L) 
    {
                
        JOptionPane.showMessageDialog(this, "Please Enter a Valid Phone No");
        PhoneTF.setText("");
                
    }

else
{
    String s1="update bank_table set Phone_no='"+(Phone)+"' where Account_no='"+(Acc)+"'";
    String s2="select * from Bank_Table where Account_no="+(Acc)+"";
    ctup(s1,s2);
}   
    
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_PhoneBTNActionPerformed

    private void DateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateBTNActionPerformed
int w=0;
String Acc=AccTF.getText(); 
String Date=DateTF.getText();
if(Acc.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter Account number");
}
else if(Date.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter a Date");
}
else
{
    SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        try {
            
            Date Acda=df.parse(Date);
            w=1;
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Date in proper format\nThat is : YYYY-MM-DD");
            DateTF.setText("");
        }

    if(w==1){
    String s1="update bank_table set Date_of_Account_Creation='"+(Date)+"' where Account_no='"+(Acc)+"'";
    String s2="select * from Bank_Table where Account_no="+(Acc)+"";
    ctup(s1,s2);
    }
    
    


}   

// TODO add your handling code here:
    }//GEN-LAST:event_DateBTNActionPerformed

    private void AccTypeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTypeBTNActionPerformed

String Acc=AccTF.getText(); 
String Type;
        if ("Current Account".equals(TypeCoB.getSelectedItem().toString())) {
            
            Type="Current Account";
            
        }else{
        
            Type="Saving Account";
            
        }

if(Acc.trim().equals(""))
{
JOptionPane.showMessageDialog(this,"Please enter Account number");
}
else
{
    String s1="update bank_table set Account_Type='"+(Type)+"' where Account_no='"+(Acc)+"'";
    String s2="select * from Bank_Table where Account_no="+(Acc)+"";
    ctup(s1,s2);
}   


// TODO add your handling code here:
    }//GEN-LAST:event_AccTypeBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed

AccTF.setText("");
CardTF.setText("");
DateTF.setText("");
NameTF.setText("");
PhoneTF.setText("");
TypeCoB.setSelectedIndex(0);
ctd("select * from Bank_Table");        
    NameBTN.setEnabled(false);

        AccTypeBTN.setEnabled(false);
        
        CardBTN.setEnabled(false);
        ClearBTN.setEnabled(false);
        DateBTN.setEnabled(false);
        DateTF.setEnabled(false);
        NameTF.setEnabled(false);
        PhoneBTN.setEnabled(false);
        PhoneTF.setEnabled(false);
        TypeCoB.setEnabled(false);
        CardTF.setEnabled(false);
    
// TODO add your handling code here:
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void CardTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardTFActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccTF;
    private javax.swing.JButton AccTypeBTN;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton CardBTN;
    private javax.swing.JTextField CardTF;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton DateBTN;
    private javax.swing.JTextField DateTF;
    private javax.swing.JTable DetailsTBL;
    private javax.swing.JButton Exit;
    private javax.swing.JButton NameBTN;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton PhoneBTN;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JComboBox TypeCoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
