
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Delete_Acccount extends javax.swing.JFrame {
int r=0;
String pwd="MyNewPass";
    /**
     * Creates new form Bank_management_system3
     */
    public Delete_Acccount() {
        initComponents();
        
        this.setSize(910,548);
        this.setLocation(220, 92);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        ctd("select * from Bank_Table");
    }
public void ctd(String qr)
{

DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            if(r==1)
            {
            
            int rows1=stmt.executeUpdate(qr);
            JOptionPane.showMessageDialog(this, "Account Deleted");
            qr="select * from Bank_Table";
            
            }
            
            ResultSet rs=stmt.executeQuery(qr);
             int rows=tm.getRowCount();
            if (rows>0) {
                
                for (int i = 0; i < rows; i++) {
                    
                    tm.removeRow(0);
                    
                }}               
            while (rs.next()) {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                tm.addRow(new Object[]{acc,name,balance,card,Acctype});
                
            }
            
        if(tm.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this, "No such Record found\nPlease enter account number correctly");
            AccTF.setText("");
            ctd("select * from Bank_Table");
        }
            
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        DeleteBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AccTF = new javax.swing.JTextField();
        ClearBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Record");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account no", "Name", "Balance", "Card no", "Account Type"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 108, 879, 220);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Delete Record");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(386, 43, 128, 22);

        DeleteBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteBTN.setText("Delete Record");
        DeleteBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBTN);
        DeleteBTN.setBounds(40, 450, 132, 30);

        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(812, 471, 61, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Account no. to be deleted");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 380, 162, 15);

        AccTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccTFKeyPressed(evt);
            }
        });
        getContentPane().add(AccTF);
        AccTF.setBounds(230, 370, 216, 30);

        ClearBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBTN);
        ClearBTN.setBounds(460, 450, 63, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Qmark.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed

        r=1;
        String Acc=AccTF.getText();
if(Acc.trim().equals("")){JOptionPane.showMessageDialog(this, "Please enter Account number");}
else{
        Acc="delete from Bank_Table where Account_no="+(Acc)+"";
        ctd(Acc);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed

        new Bank_management_system().setVisible(true);
        this.setVisible(false);   // exit the frame

        // TODO add your handling code here:
    }//GEN-LAST:event_BackBTNActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void AccTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccTFKeyPressed
r=2;
if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
        String Acc=AccTF.getText();
if(Acc.trim().equals("")){JOptionPane.showMessageDialog(this, "Please enter Account number");}
else
{
    Acc="select * from Bank_Table where Account_no="+(Acc)+"";
    ctd(Acc);
}       
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_AccTFKeyPressed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
r=3;
AccTF.setText("");
String d="select * from Bank_Table";
ctd(d);

    }//GEN-LAST:event_ClearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Acccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Acccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Acccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Acccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Acccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccTF;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
