
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public Login() {
        initComponents();
        
        this.setLocation(260,120);
        this.setSize(745,479);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        PassPF = new javax.swing.JPasswordField();
        LoginBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main_Frame");
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 130, 180, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 200, 150, 22);

        NameTF.setToolTipText("Enter the account name");
        getContentPane().add(NameTF);
        NameTF.setBounds(370, 130, 205, 30);

        PassPF.setToolTipText("Enter the password");
        PassPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassPFKeyPressed(evt);
            }
        });
        getContentPane().add(PassPF);
        PassPF.setBounds(370, 200, 205, 30);

        LoginBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginBTN.setText("Login");
        LoginBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        LoginBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginBTNKeyPressed(evt);
            }
        });
        getContentPane().add(LoginBTN);
        LoginBTN.setBounds(260, 360, 167, 46);

        ExitBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBTN);
        ExitBTN.setBounds(660, 410, 66, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

public int log=0; 
private int login(){
String Username = NameTF.getText().trim();
String Password = new String(PassPF.getPassword()).trim();
if ("xyz".equals(Username)&&"xxyyzz".equals(Password)) 
{
new Bank_management_system().setVisible(true);
this.setVisible(false);

} else if (!"xyz".equals(Username)||!"xxyyzz".equals(Password)) {
log++;
}
if (log==2) {
JOptionPane.showMessageDialog(this, "One chance left");
}
if (log==3) {
System.exit(0);  
}
return log;   
}

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed

login();        
        
// TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNActionPerformed

    private void PassPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassPFKeyPressed

        if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            
             login();  
             
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_PassPFKeyPressed

    private void LoginBTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginBTNKeyPressed

        if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            
            login(); 
            
        }  
        
// TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNKeyPressed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed

System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_ExitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JTextField NameTF;
    private javax.swing.JPasswordField PassPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
