
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Compaq
 */
public class Modify_Account extends javax.swing.JFrame {
String pwd="MyNewPass";
    /**
     * Creates new form Bank_management_system4
     */
    public Modify_Account() {
        initComponents();
        
        this.setSize(1024,665);
        this.setLocation(160,50);
        AccNoTF.setFocusable(false);
        NameTF.setFocusable(false);
               
        cty();
      
        jRadioButton2.setSelected(true);
        AccTF.setEnabled(true);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        
    }

    public void cta(String qry)
    {
        DefaultTableModel tm=(DefaultTableModel)ModifyTBL.getModel();
        try {
            int rows=tm.getRowCount();
            if (rows>0) 
            {
                for (int i = 0; i < rows; i++) 
                {
                    tm.removeRow(0);
                }
            }
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(qry);
            while (rs.next()) {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                tm.addRow(new Object[]{acc,name,balance,Acctype});             
                AccNoTF.setText(acc);
                NameTF.setText(name);      
                
            }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        
        EnterNameTF.setText("");
          
        if(tm.getRowCount()==0)
        {
        JOptionPane.showMessageDialog(this, "No Such Record exists\nPlease enter details correctly ");
        cty();
        AccTF.setText("");
        
        }   
    }
    public void cty()
            {
            DefaultTableModel tm=(DefaultTableModel)ModifyTBL.getModel();
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from Bank_Table");
            
            int rows=tm.getRowCount();
            if (rows>0) 
            {
                for (int i = 0; i < rows; i++) 
                {
                    tm.removeRow(0);
                    
                }
            }               
            while (rs.next()) 
            {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                tm.addRow(new Object[]{acc,name,balance,Acctype});
                
            }
            
        } 
        catch (Exception e) 
        {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UpdateBTN = new javax.swing.JButton();
        DetailsBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        BalanceTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        EnterNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        AccTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AccNoTF = new javax.swing.JTextField();
        BackBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModifyTBL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modify Account");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Modifying the Record");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(417, 11, 192, 22);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        UpdateBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateBTN.setText("Update Balance");
        UpdateBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBTN);
        UpdateBTN.setBounds(400, 560, 150, 40);

        DetailsBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DetailsBTN.setText("Change Other Details");
        DetailsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsBTNActionPerformed(evt);
            }
        });
        jPanel1.add(DetailsBTN);
        DetailsBTN.setBounds(600, 560, 170, 40);

        ClearBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ClearBTN);
        ClearBTN.setBounds(230, 560, 110, 40);
        jPanel1.add(BalanceTF);
        BalanceTF.setBounds(460, 480, 196, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        EnterNameTF.setEnabled(false);
        EnterNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNameTFActionPerformed(evt);
            }
        });
        EnterNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterNameTFKeyPressed(evt);
            }
        });
        jPanel2.add(EnterNameTF);
        EnterNameTF.setBounds(200, 140, 196, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search by  Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 150, 110, 15);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(10, 140, 20, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("OR");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 110, 30, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Search by Account no");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(40, 70, 131, 15);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(10, 60, 20, 21);

        AccTF.setEnabled(false);
        AccTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccTFActionPerformed(evt);
            }
        });
        AccTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AccTFKeyPressed(evt);
            }
        });
        jPanel2.add(AccTF);
        AccTF.setBounds(200, 60, 196, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search By:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(70, 250, 420, 200);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Change Balance:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 480, 120, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Account no");

        AccNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccNoTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(NameTF))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AccNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(620, 270, 350, 150);

        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BackBTN);
        BackBTN.setBounds(950, 600, 61, 23);

        ModifyTBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ModifyTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account no", "Name", "Balance", "Account Type"
            }
        ));
        ModifyTBL.setEnabled(false);
        jScrollPane2.setViewportView(ModifyTBL);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 70, 940, 158);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 640);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search by  Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(573, 272, 110, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Search by Account no");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(125, 272, 131, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Search by Account no");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(125, 272, 131, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Frame(){
     
        if (new Modify_Account().isShowing()) {
          new Login().setVisible(true);
          this.setVisible(false);
        }
 
    
    }
    
    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed

DefaultTableModel tm=(DefaultTableModel)ModifyTBL.getModel();        
String Balance=BalanceTF.getText();
String Acc=AccNoTF.getText();
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root",pwd);
            Statement stmt=con.createStatement();
            ResultSet bal=stmt.executeQuery("select * from Bank_Table where Account_no='"+(Acc)+"'");
            String amount="";           
            while (bal.next()) {                
                
                amount=bal.getString("Balance");
                
            }
            if (Integer.parseInt(amount)<500&&Integer.parseInt(Balance)>500) {
                
                JOptionPane.showMessageDialog(this, "A Fine of Rs. 50 will be Charged");
                Balance=Integer.toString(Integer.parseInt(Balance)-50);
                
            }
            int rows=stmt.executeUpdate("update Bank_Table set Balance="+(Balance)+" where Account_no="+(Acc)+"");            
            ResultSet rs=stmt.executeQuery("select * from Bank_Table where Account_no='"+(Acc)+"'");
            if (rows>0) {
                
                for (int i = 0; i < rows; i++) {
                    
                    tm.removeRow(0);
                    
                }}               
            while (rs.next()) {                
                
                String acc=rs.getString("Account_no");
                String name=rs.getString("Name_of_Account_Holder");
                String balance=rs.getString("Balance");
                String card=rs.getString("Card_no");
                String Acctype=rs.getString("Account_Type");
                tm.addRow(new Object[]{acc,name,balance,Acctype});
                                            
            }
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this,"Plaese enter details properly");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed

        new Bank_management_system().setVisible(true);
        this.setVisible(false);  // exit the frame

        // TODO add your handling code here:
    }//GEN-LAST:event_BackBTNActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void AccTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccTFKeyPressed

String Acc=AccTF.getText();
Acc="select * from Bank_Table where Account_no='"+(Acc)+"'";
        if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            cta(Acc);
        }                

// TODO add your handling code here:
    }//GEN-LAST:event_AccTFKeyPressed

    private void DetailsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsBTNActionPerformed
              
new Admin_Login().setVisible(true);
this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_DetailsBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed

        AccTF.setText("");
        AccNoTF.setText("");
        NameTF.setText("");
        BalanceTF.setText("");
        cty();
        
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void EnterNameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterNameTFKeyPressed

String Name=EnterNameTF.getText();
Name="select * from Bank_Table where Name_of_Account_Holder='"+(Name)+"'";
if ("Enter".equals(KeyEvent.getKeyText(evt.getKeyCode()))) {
            
          cta(Name); 
        }         

// TODO add your handling code here:
    }//GEN-LAST:event_EnterNameTFKeyPressed

    private void AccNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccNoTFActionPerformed

    private void EnterNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNameTFActionPerformed

    private void AccTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccTFActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        EnterNameTF.setEnabled(false);
        AccTF.setEnabled(true);
        EnterNameTF.setText("");

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        AccTF.setEnabled(false);
        EnterNameTF.setEnabled(true);
        AccTF.setText("");
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNoTF;
    private javax.swing.JTextField AccTF;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTextField BalanceTF;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton DetailsBTN;
    private javax.swing.JTextField EnterNameTF;
    private javax.swing.JTable ModifyTBL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
