
import java.awt.Color;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajeev
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        
        this.setSize(660, 515);
        this.setLocation(300,120);
        URL resource = Login.class.getResource("Images/institution_icon.png");                
        ImageIcon icon = new ImageIcon(resource);               
        this.setIconImage(icon.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        Continue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Bank Management Application");
        setResizable(false);
        getContentPane().setLayout(null);

        jLayeredPane2.setMinimumSize(new java.awt.Dimension(661, 495));

        Continue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Continue.setText("Continue");
        Continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContinueMouseExited(evt);
            }
        });
        jLayeredPane2.add(Continue);
        Continue.setBounds(550, 450, 90, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Created By:");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(10, 370, 160, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture1.png"))); // NOI18N
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(10, 380, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome.png"))); // NOI18N
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 500);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(0, -10, 670, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseEntered

Continue.setForeground(Color.WHITE);

// TODO add your handling code here:
    }//GEN-LAST:event_ContinueMouseEntered

    private void ContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseExited

Continue.setForeground(Color.BLACK);

// TODO add your handling code here:
    }//GEN-LAST:event_ContinueMouseExited

    private void ContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseClicked

new Login().setVisible(true);
this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_ContinueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Continue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
